family = ['Sandra','Juan','Jhoan','Devin','Adrian','Daniela','Isa','Hernan','Mylenne','Sebas','Alejandro','Haydee','Percy','Gerardo','Dani','Adriana','Ruth','Viviana','Wagner','Damian']
print(family[0:3])
print(family[2:4])
print(family[:3])
print(family[2:])
print(family[-2:])
print(family[1:5])
print(family[:-1])
print(family[-1:])
print(family[-3:])
print(family[8:9])